workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.5
      xcode: 15.0
    scripts:
      - name: Run Flutter Pub Get
        script: flutter pub get
      - name: Ensure `podhelper.rb` exists
        script: |
          cd ios/.ios/Flutter
          if [ ! -f "podhelper.rb" ]; then
            echo "Creating podhelper.rb manually"
            echo "# podhelper.rb" > podhelper.rb
            echo "require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'), Dir.pwd)" >> podhelper.rb
            echo "flutter_application_path = File.expand_path('..', __dir__)" >> podhelper.rb
            echo "flutter_install_all_ios_pods(flutter_application_path)" >> podhelper.rb
          fi
      - name: Set iOS deployment target
        script: |
          cd ios
          echo "Setting iOS deployment target in Podfile"
          if ! grep -q "platform :ios, '13.0'" Podfile; then
            sed -i '' '1s/^/platform :ios, "13.0"\n/' Podfile
          fi
      - name: Install CocoaPods
        script: pod install --repo-update
    artifacts:
      - build/ios/ipa
