workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.5
      xcode: 15.0
    scripts:
      - name: Run Flutter Pub Get
        script: flutter pub get

      - name: Clean Build Artifacts
        script: flutter clean

      - name: Generate flutter_export_environment.sh
        script: |
          # Navigate to the Flutter iOS directory
          cd ios/Flutter
          # Check if flutter_export_environment.sh exists, if not, create it
          if [ ! -f "flutter_export_environment.sh" ]; then
            echo "Creating flutter_export_environment.sh file..."
            echo "export FLUTTER_ROOT=${FLUTTER_ROOT}" > flutter_export_environment.sh
            echo "export FLUTTER_APPLICATION_PATH=${PWD}" >> flutter_export_environment.sh
            echo "export COCOAPODS_PARALLEL_CODE_SIGN=true" >> flutter_export_environment.sh
          fi
          # Display file content for verification
          cat flutter_export_environment.sh

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Release
        script: |
          flutter build ios --release --no-codesign || {
            echo "Build failed due to issues with dependencies.";
            exit 1;
          }

    artifacts:
      - build/ios/ipa

    publishing:
      email:
        recipients:
          - gujjarji7838@gmail.com

          
