workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.5
      xcode: 15.0
    scripts:
      - name: Set iOS deployment target
        script: |
          cd ios
          echo "Setting iOS deployment target in Podfile"
          if ! grep -q "platform :ios, '13.0'" Podfile; then
            sed -i '' '1s/^/platform :ios, "13.0"\n/' Podfile
          fi
          pod install --repo-update
    artifacts:
      - build/ios/ipa
