workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.5
      xcode: 15.0
    scripts:
      - name: Run Flutter Pub Get
        script: flutter pub get
      - name: Build iOS project to generate podhelper.rb
        script: flutter build ios --no-codesign
      - name: Verify podhelper.rb file exists
        script: |
          if [ ! -f ios/.ios/Flutter/podhelper.rb ]; then
            echo "Error: podhelper.rb not found. Exiting."
            exit 1
          else
            echo "podhelper.rb found. Proceeding with pod install."
          fi
      - name: Set iOS deployment target
        script: |
          cd ios
          echo "Setting iOS deployment target in Podfile"
          if ! grep -q "platform :ios, '13.0'" Podfile; then
            sed -i '' '1s/^/platform :ios, "13.0"\n/' Podfile
          fi
      - name: Install CocoaPods
        script: pod install --repo-update
    artifacts:
      - build/ios/ipa
