workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.5
      xcode: 15.0
    scripts:
      - name: Clean Build Artifacts
        script: flutter clean

      - name: Run Flutter Pub Get
        script: flutter pub get

      - name: Generate flutter_export_environment.sh
        script: |
          cd ios/Flutter
          if [ ! -f "flutter_export_environment.sh" ]; then
            echo "export FLUTTER_ROOT=${FLUTTER_ROOT}" > flutter_export_environment.sh
            echo "export FLUTTER_APPLICATION_PATH=${PWD}" >> flutter_export_environment.sh
            echo "export COCOAPODS_PARALLEL_CODE_SIGN=true" >> flutter_export_environment.sh
          fi
          cat flutter_export_environment.sh

      - name: Update Ruby Version
        script: |
          ruby_version=3.1.4
          rbenv install -s $ruby_version
          rbenv global $ruby_version
          ruby -v

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod --version

      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS Release
        script: |
          flutter build ios --release --no-codesign || {
            echo "Build failed due to issues with dependencies.";
            exit 1;
          }

    artifacts:
      - build/ios/ipa

    publishing:
      email:
        recipients:
          - gujjarji7838@gmail.com
