flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')
load File.join(flutter_application_path, 'ios', 'Flutter', 'flutter_export_environment.sh')  # This line ensures the script is loaded

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)
end
