platform :ios, '13.0'

inhibit_all_warnings!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = File.expand_path('..', __dir__)
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  flutter_install_all_ios_pods(flutter_application_path)
end
